"""add payment paid

Revision ID: 5cd99727c84c
Revises: b88d5ca7c733
Create Date: 2024-10-09 17:26:42.952233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd99727c84c'
down_revision: Union[str, None] = 'b88d5ca7c733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'paid')
    # ### end Alembic commands ###
