"""add user columns for referrals

Revision ID: 973df9969834
Revises: f3d1a1558f8b
Create Date: 2024-10-09 16:07:03.929564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973df9969834'
down_revision: Union[str, None] = 'f3d1a1558f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('tariff_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('invited_by', sa.BIGINT(), nullable=True))
    op.add_column('users', sa.Column('friends', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('bonuses', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'users', ['invited_by'], ['id'])
    op.create_foreign_key(None, 'users', 'tariffs', ['tariff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'bonuses')
    op.drop_column('users', 'friends')
    op.drop_column('users', 'invited_by')
    op.drop_column('users', 'tariff_id')
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
