"""user new

Revision ID: c4d1df2bd42f
Revises: ab89aedb077f
Create Date: 2024-10-12 22:05:48.115445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d1df2bd42f'
down_revision: Union[str, None] = 'ab89aedb077f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new')
    # ### end Alembic commands ###
