"""add orders

Revision ID: db1be0b64d94
Revises: cb7fce3bb41f
Create Date: 2024-10-10 16:32:45.158584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1be0b64d94'
down_revision: Union[str, None] = 'cb7fce3bb41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payments', sa.Column('amount', sa.Integer(), nullable=False))
    op.drop_constraint('payments_tariff_id_fkey', 'payments', type_='foreignkey')
    op.drop_column('payments', 'tariff_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('tariff_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('payments_tariff_id_fkey', 'payments', 'tariffs', ['tariff_id'], ['id'])
    op.drop_column('payments', 'amount')
    op.drop_table('orders')
    # ### end Alembic commands ###
